In [1]:
def func_nam(a,b):
    c = a + b
    return c

In [2]:
def score_label(score):
    if score >= 90:
        return "Excellent"
    elif score >= 70:
        return "Good"
    elif score >= 50:
        return "Pass"
    else:
        return "Fail"

score_label(85)

'Good'

In [3]:
import pandas as pd

df_scores = pd.DataFrame({
    "student": ["Anna", "Ben", "Chris", "Diana", "Eva"],
    "score": [95, 78, 61, 43, 88]
})

df_scores

  student  score
0    Anna     95
1     Ben     78
2   Chris     61
3   Diana     43
4     Eva     88

In [4]:
df_scores["score_label"] = df_scores["score"].apply(score_label)
df_scores

  student  score score_label
0    Anna     95   Excellent
1     Ben     78        Good
2   Chris     61        Pass
3   Diana     43        Fail
4     Eva     88        Good

In [5]:
df_scores["score_label"] = [score_label(i) for i in df_scores["score"]]
df_scores

  student  score score_label
0    Anna     95   Excellent
1     Ben     78        Good
2   Chris     61        Pass
3   Diana     43        Fail
4     Eva     88        Good

In [6]:
def classify_price(price, low=5, high=15):
    if price <= low:
        return "Low-range product"
    elif price <= high:
        return "Mid-range product"
    else:
        return "High-range product"

classify_price(9)

'Mid-range product'

In [7]:
classify_price(9, low=3, high=10)

'Mid-range product'

In [8]:
df_products_dummy = pd.DataFrame({
    "product": ["Milk", "Bread", "Juice", "Cheese", "Steak", "Apples"],
    "price": [2.5, 1.8, 6.2, 12.0, 24.5, 4.2]
})

df_products_dummy

  product  price
0    Milk    2.5
1   Bread    1.8
2   Juice    6.2
3  Cheese   12.0
4   Steak   24.5
5  Apples    4.2

In [9]:
df_products_dummy["price_range"] = df_products_dummy["price"].apply(classify_price)
df_products_dummy

  product  price         price_range
0    Milk    2.5   Low-range product
1   Bread    1.8   Low-range product
2   Juice    6.2   Mid-range product
3  Cheese   12.0   Mid-range product
4   Steak   24.5  High-range product
5  Apples    4.2   Low-range product

In [10]:
if price <= 5:
    label = "Low-range product"
elif price <= 15:
    label = "Mid-range product"
else:
    label = "High-range product"

NameError: name 'price' is not defined

In [11]:
df_customers_dummy = pd.DataFrame({
    "customer": ["A", "B", "C", "D", "E"],
    "age": [22, 35, 47, 63, 29],
    "income": [18000, 42000, 72000, 95000, 25000]
})

df_customers_dummy

  customer  age  income
0        A   22   18000
1        B   35   42000
2        C   47   72000
3        D   63   95000
4        E   29   25000

In [12]:
def age_group_label(age):
    if age < 30:
        return "Young"
    elif age < 60:
        return "Middle"
    else:
        return "Senior"

df_customers_dummy["age_group"] = df_customers_dummy["age"].apply(age_group_label)
df_customers_dummy

  customer  age  income age_group
0        A   22   18000     Young
1        B   35   42000    Middle
2        C   47   72000    Middle
3        D   63   95000    Senior
4        E   29   25000     Young