Datetime

In [1]:
x = 42
from datetime import datetime, date, timedelta

In [2]:
simple_date = date(2024, 7, 1)
simple_date

datetime.date(2024, 7, 1)

In [3]:
full_datetime = datetime(2024, 7, 1, 14, 30, 0)
full_datetime

datetime.datetime(2024, 7, 1, 14, 30)

In [4]:
today = date.today()
now = datetime.now()

print(f'todaye is {today}')
print(f'right now is {now}')

todaye is 2026-05-13
right now is 2026-05-13 23:04:09.052985

In [5]:
print(f"Year: {full_datetime.year}")
print(f"Month: {full_datetime.month}")
print(f"Day: {full_datetime.day}")
print(f"Hour: {full_datetime.hour}")
print(f"Minute: {full_datetime.minute}")
print(f"Second: {full_datetime.second}")

Year: 2024
Month: 7
Day: 1
Hour: 14
Minute: 30
Second: 0

In [6]:
full_datetime.strftime("%Y-%m-%d")

'2024-07-01'

In [7]:
full_datetime.strftime("%d/%m/%Y")

'01/07/2024'

In [8]:
full_datetime.strftime("%B %d, %Y")

'July 01, 2024'

In [9]:
dt = datetime.strptime("2024-07-01", "%Y-%m-%d")
dt

datetime.datetime(2024, 7, 1, 0, 0)

In [10]:
start = date(2024, 7, 1)
end = date(2024, 7, 15)

delta = end - start
delta

datetime.timedelta(days=14)

In [11]:
delta.days

14

In [12]:
start + timedelta(days=10)

datetime.date(2024, 7, 11)

In [13]:
start - timedelta(days=7)

datetime.date(2024, 6, 24)

In [14]:
print(start + timedelta(days=10))
print(start - timedelta(days=7))
print(start + timedelta(weeks=2))
print(start - timedelta(weeks=1))

2024-07-11
2024-06-24
2024-07-15
2024-06-24

In [15]:
start_dt = datetime(2024, 7, 1, 14, 30, 0)

print(start_dt + timedelta(days=1))
print(start_dt + timedelta(hours=5))
print(start_dt + timedelta(minutes=45))
print(start_dt + timedelta(seconds=30))
print(start_dt + timedelta(days=2, hours=3, minutes=15, seconds=10))

2024-07-02 14:30:00
2024-07-01 19:30:00
2024-07-01 15:15:00
2024-07-01 14:30:30
2024-07-03 17:45:10

Dates in Pandas

In [16]:
import pandas as pd

df_dates = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "signup_date": ["2024-01-15", "2024-02-20", "2024-03-05", "2024-03-18", "2024-04-10"],
    "last_purchase": ["2024-06-01", "2024-06-15", "2024-07-01", "2024-07-08", "2024-07-12"]
})

df_dates

   customer_id signup_date last_purchase
0          101  2024-01-15    2024-06-01
1          102  2024-02-20    2024-06-15
2          103  2024-03-05    2024-07-01
3          104  2024-03-18    2024-07-08
4          105  2024-04-10    2024-07-12

In [17]:
df_dates.dtypes

customer_id      int64
signup_date        str
last_purchase      str
dtype: object

In [18]:
df_dates["signup_date"] = pd.to_datetime(df_dates["signup_date"])
df_dates["last_purchase"] = pd.to_datetime(df_dates["last_purchase"])

df_dates.dtypes

customer_id               int64
signup_date      datetime64[us]
last_purchase    datetime64[us]
dtype: object

In [19]:
df_dates["signup_year"] = df_dates["signup_date"].dt.year
df_dates["signup_month"] = df_dates["signup_date"].dt.month
df_dates["signup_day"] = df_dates["signup_date"].dt.day

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day
0,101,2024-01-15,2024-06-01,2024,1,15
1,102,2024-02-20,2024-06-15,2024,2,20
2,103,2024-03-05,2024-07-01,2024,3,5
3,104,2024-03-18,2024-07-08,2024,3,18
4,105,2024-04-10,2024-07-12,2024,4,10

In [20]:
df_dates["signup_month_name"] = df_dates["signup_date"].dt.month_name()
df_dates["signup_day_name"] = df_dates["signup_date"].dt.day_name()

df_dates[["signup_date", "signup_month_name", "signup_day_name"]]

  signup_date signup_month_name signup_day_name
0  2024-01-15           January          Monday
1  2024-02-20          February         Tuesday
2  2024-03-05             March         Tuesday
3  2024-03-18             March          Monday
4  2024-04-10             April       Wednesday

In [21]:
df_dates["signup_quarter"] = df_dates["signup_date"].dt.quarter
df_dates[["signup_date", "signup_quarter"]]

  signup_date  signup_quarter
0  2024-01-15               1
1  2024-02-20               1
2  2024-03-05               1
3  2024-03-18               1
4  2024-04-10               2

In [22]:
df_dates["signup_dow"] = df_dates["signup_date"].dt.dayofweek
df_dates[["signup_date", "signup_dow"]]

  signup_date  signup_dow
0  2024-01-15           0
1  2024-02-20           1
2  2024-03-05           1
3  2024-03-18           0
4  2024-04-10           2

In [23]:
df_dates["is_weekend"] = (df_dates["signup_date"].dt.dayofweek >= 5).astype(int)
df_dates[["signup_date", "signup_dow", "is_weekend"]]

  signup_date  signup_dow  is_weekend
0  2024-01-15           0           0
1  2024-02-20           1           0
2  2024-03-05           1           0
3  2024-03-18           0           0
4  2024-04-10           2           0

In [24]:
df_dates["days_between_signup_and_purchase"] = (
    df_dates["last_purchase"] - df_dates["signup_date"]
).dt.days

df_dates[["signup_date", "last_purchase", "days_between_signup_and_purchase"]]

  signup_date last_purchase  days_between_signup_and_purchase
0  2024-01-15    2024-06-01                               138
1  2024-02-20    2024-06-15                               116
2  2024-03-05    2024-07-01                               118
3  2024-03-18    2024-07-08                               112
4  2024-04-10    2024-07-12                                93

In [25]:
##Filter Rows After a Given Date
df_dates[df_dates["signup_date"] >= "2024-03-01"]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [26]:
df_dates[df_dates["signup_date"].dt.month == 3]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112

In [27]:
df_dates[df_dates["signup_date"].dt.year == 2024]

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [28]:
##Sorting by Date
df_dates.sort_values("signup_date")

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,1,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,3,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,3,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,4,10,April,Wednesday,2,2,0,93

In [29]:
##Creating Date Ranges
pd.date_range(start="2024-07-01", periods=7, freq="D")

DatetimeIndex(['2024-07-01', '2024-07-02', '2024-07-03', '2024-07-04',
               '2024-07-05', '2024-07-06', '2024-07-07'],
              dtype='datetime64[us]', freq='D')

In [30]:
pd.date_range(start="2024-01-01", periods=6, freq="MS")

DatetimeIndex(['2024-01-01', '2024-02-01', '2024-03-01', '2024-04-01',
               '2024-05-01', '2024-06-01'],
              dtype='datetime64[us]', freq='MS')

In [31]:
import pandas as pd

some_date = pd.Timestamp("2024-07-15")

print(f"Original date: {some_date}")
print(f"Beginning of month: {some_date.to_period('M').start_time}")
print(f"End of month: {some_date.to_period('M').end_time}")

Original date: 2024-07-15 00:00:00
Beginning of month: 2024-07-01 00:00:00
End of month: 2024-07-31 23:59:59.999999

In [32]:
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.start_time
df_dates["signup_month"] = df_dates["signup_date"].dt.to_period("M").dt.end_time

df_dates

,customer_id,signup_date,last_purchase,signup_year,signup_month,signup_day,signup_month_name,signup_day_name,signup_quarter,signup_dow,is_weekend,days_between_signup_and_purchase
0,101,2024-01-15,2024-06-01,2024,2024-01-31 23:59:59.999999,15,January,Monday,1,0,0,138
1,102,2024-02-20,2024-06-15,2024,2024-02-29 23:59:59.999999,20,February,Tuesday,1,1,0,116
2,103,2024-03-05,2024-07-01,2024,2024-03-31 23:59:59.999999,5,March,Tuesday,1,1,0,118
3,104,2024-03-18,2024-07-08,2024,2024-03-31 23:59:59.999999,18,March,Monday,1,0,0,112
4,105,2024-04-10,2024-07-12,2024,2024-04-30 23:59:59.999999,10,April,Wednesday,2,2,0,93