In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [2]:
px.defaults.template = "plotly_white"

Bar Plot

In [3]:
region_sales = (
    df_plotly.groupby("region", as_index=False)["sales"]
             .sum()
)

region_sales

  region  sales
0   East   1559
1  North   1800
2  South   1674

In [5]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    text="sales",
    title="Total Sales by Region"
)

fig.update_traces(textposition="outside")
fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'region=%{x}<br>sales=%{text}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'text': {'bdata': 'AAAAAABcmEAAAAAAACCcQAAAAAAAKJpA', 'dtype': 'f8'},
              'textposition': 'outside',
              'type': 'bar',
              'x': array(['East', 'North', 'South'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'FwYIB4oG', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Total Sales by Region'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Region'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}}}
})

Line Plot

In [6]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [8]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'month=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array(['2024-01-01T00:00:00.000000', '2024-02-01T00:00:00.000000',
                          '2024-03-01T00:00:00.000000', '2024-04-01T00:00:00.000000',
                          '2024-05-01T00:00:00.000000', '2024-06-01T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': 'JwMqAz8DVwOmAxwD', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Monthly Total Sales'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Month'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}}}
})

Histogram

In [9]:
fig = px.histogram(
    df_plotly,
    x="sales",
    nbins=15,
    title="Distribution of Sales"
)

fig.update_layout(
    xaxis_title="Sales",
    yaxis_title="Count"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'bingroup': 'x',
              'hovertemplate': 'sales=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': '',
              'nbinsx': 15,
              'orientation': 'v',
              'showlegend': False,
              'type': 'histogram',
              'x': {'bdata': ('tgBeALYAhAB1AGQAiQCoAIoAXgCCAI' ... 'DLAF4AqADQAI4AoABwAHgAlwBwAI0A'),
                    'dtype': 'i2'},
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Distribution of Sales'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Count'}}}
})

Scatter Plot

In [10]:
fig = px.scatter(
    df_plotly,
    x="customers",
    y="sales",
    color="region",
    hover_data=["product", "month_name", "units"],
    title="Customers vs Sales"
)

fig.update_layout(
    xaxis_title="Customers",
    yaxis_title="Sales",
    legend_title="Region"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'customdata': array([['A', 'Jan', 38],
                                   ['B', 'Jan', 30],
                                   ['A', 'Feb', 53],
                                   ['B', 'Feb', 36],
                                   ['A', 'Mar', 30],
                                   ['B', 'Mar', 27],
                                   ['A', 'Apr', 59],
                                   ['B', 'Apr', 11],
                                   ['A', 'May', 33],
                                   ['B', 'May', 38],
                                   ['A', 'Jun', 44],
                                   ['B', 'Jun', 51]], dtype=object),
              'hovertemplate': ('region=North<br>customers=%{x}' ... '{customdata[2]}<extra></extra>'),
              'legendgroup': 'North',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'North',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'R1ApRBo6NxdIPBsY', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': {'bdata': 'tgBeAIkAqACCAJgAoAC3AHcAywCgAHAA', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'customdata': array([['A', 'Jan', 12],
                                   ['B', 'Jan', 33],
                                   ['A', 'Feb', 37],
                                   ['B', 'Feb', 56],
                                   ['A', 'Mar', 23],
                                   ['B', 'Mar', 11],
                                   ['A', 'Apr', 51],
                                   ['B', 'Apr', 38],
                                   ['A', 'May', 10],
                                   ['B', 'May', 33],
                                   ['A', 'Jun', 16],
                                   ['B', 'Jun', 43]], dtype=object),
              'hovertemplate': ('region=South<br>customers=%{x}' ... '{customdata[2]}<extra></extra>'),
              'legendgroup': 'South',
              'marker': {'color': '#EF553B', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'South',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'KxU9UU9ISUlAHC8f', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': {'bdata': 'tgCEAIoAXgDTAFgA1QBTAF4AqAB4AJcA', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'customdata': array([['A', 'Jan', 69],
                                   ['B', 'Jan', 21],
                                   ['A', 'Feb', 61],
                                   ['B', 'Feb', 46],
                                   ['A', 'Mar', 16],
                                   ['B', 'Mar', 44],
                                   ['A', 'Apr', 19],
                                   ['B', 'Apr', 24],
                                   ['A', 'May', 33],
                                   ['B', 'May', 60],
                                   ['A', 'Jun', 64],
                                   ['B', 'Jun', 44]], dtype=object),
              'hovertemplate': ('region=East<br>customers=%{x}<' ... '{customdata[2]}<extra></extra>'),
              'legendgroup': 'East',
              'marker': {'color': '#00cc96', 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'East',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': {'bdata': 'FTRKFk9CNUMbHkM4', 'dtype': 'i1'},
              'xaxis': 'x',
              'y': {'bdata': 'dQBkAIIAjwCjAFcAewBdANAAjgBwAI0A', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Region'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Customers vs Sales'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Customers'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}}}
})

Multi-Line Chart

In [11]:
monthly_region_sales = (
    df_plotly.groupby(["month", "region"], as_index=False)["sales"]
             .sum()
)

monthly_region_sales.head()

       month region  sales
0 2024-01-01   East    217
1 2024-01-01  North    276
2 2024-01-01  South    314
3 2024-02-01   East    273
4 2024-02-01  North    305

In [13]:
fig = px.line(
    monthly_region_sales,
    x="month",
    y="sales",
    color="region",
    markers=True,
    title="Monthly Sales by Region"
)

fig.update_layout(
    xaxis_title="Month",
    yaxis_title="Sales",
    legend_title="Region"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'region=East<br>month=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': 'East',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': 'East',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2024-01-01T00:00:00.000000', '2024-02-01T00:00:00.000000',
                          '2024-03-01T00:00:00.000000', '2024-04-01T00:00:00.000000',
                          '2024-05-01T00:00:00.000000', '2024-06-01T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': '2QARAfoA2ABeAf0A', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'hovertemplate': 'region=North<br>month=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': 'North',
              'line': {'color': '#EF553B', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': 'North',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2024-01-01T00:00:00.000000', '2024-02-01T00:00:00.000000',
                          '2024-03-01T00:00:00.000000', '2024-04-01T00:00:00.000000',
                          '2024-05-01T00:00:00.000000', '2024-06-01T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': 'FAExARoBVwFCARAB', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'hovertemplate': 'region=South<br>month=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': 'South',
              'line': {'color': '#00cc96', 'dash': 'solid'},
              'marker': {'symbol': 'circle'},
              'mode': 'lines+markers',
              'name': 'South',
              'orientation': 'v',
              'showlegend': True,
              'type': 'scatter',
              'x': array(['2024-01-01T00:00:00.000000', '2024-02-01T00:00:00.000000',
                          '2024-03-01T00:00:00.000000', '2024-04-01T00:00:00.000000',
                          '2024-05-01T00:00:00.000000', '2024-06-01T00:00:00.000000'],
                         dtype='datetime64[us]'),
              'xaxis': 'x',
              'y': {'bdata': 'OgHoACsBKAEGAQ8B', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'legend': {'title': {'text': 'Region'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Monthly Sales by Region'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Month'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}}}
})

In [ ]:
Grouped Bar Plot

In [14]:
region_product_sales = (
    df_plotly.groupby(["region", "product"], as_index=False)["sales"]
             .sum()
)

region_product_sales

  region product  sales
0   East       A    853
1   East       B    706
2  North       A    888
3  North       B    912
4  South       A    958
5  South       B    716

In [15]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product"
)

fig.update_layout(
    xaxis_title="Region",
    yaxis_title="Sales",
    legend_title="Product"
)

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'product=A<br>region=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': 'A',
              'marker': {'color': '#636efa', 'pattern': {'shape': ''}},
              'name': 'A',
              'offsetgroup': 'A',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['East', 'North', 'South'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'VQN4A74D', 'dtype': 'i2'},
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'product=B<br>region=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': 'B',
              'marker': {'color': '#EF553B', 'pattern': {'shape': ''}},
              'name': 'B',
              'offsetgroup': 'B',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['East', 'North', 'South'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'wgKQA8wC', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'group',
               'legend': {'title': {'text': 'Product'}, 'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Sales by Region and Product'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'Region'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'Sales'}}}
})

In [ ]:
Donut Chart

In [16]:
product_sales = (
    df_plotly.groupby("product", as_index=False)["sales"]
             .sum()
)

product_sales

  product  sales
0       A   2699
1       B   2334

In [18]:
fig = px.pie(
    product_sales,
    names="product",
    values="sales",
    hole=0.5,
    title="Share of Total Sales by Product"
)

fig.update_traces(textinfo="label+percent")

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
              'hole': 0.5,
              'hovertemplate': 'product=%{label}<br>sales=%{value}<extra></extra>',
              'labels': array(['A', 'B'], dtype=object),
              'legendgroup': '',
              'name': '',
              'showlegend': True,
              'textinfo': 'label+percent',
              'type': 'pie',
              'values': {'bdata': 'iwoeCQ==', 'dtype': 'i2'}}],
    'layout': {'legend': {'tracegroupgap': 0}, 'template': '...', 'title': {'text': 'Share of Total Sales by Product'}}
})

In [24]:
fig = px.bar(
    region_sales,
    x="region",
    y="sales",
    title="Total Sales by Region",
    color_discrete_sequence=["#a34e31"]
)

In [26]:
fig.show

<bound method BaseFigure.show of Figure({
    'data': [{'hovertemplate': 'region=%{x}<br>sales=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#a34e31', 'pattern': {'shape': ''}},
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'textposition': 'auto',
              'type': 'bar',
              'x': array(['East', 'North', 'South'], dtype=object),
              'xaxis': 'x',
              'y': {'bdata': 'FwYIB4oG', 'dtype': 'i2'},
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'tracegroupgap': 0},
               'template': '...',
               'title': {'text': 'Total Sales by Region'},
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'region'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'sales'}}}
})>

In [28]:
fig = px.bar(
    region_product_sales,
    x="region",
    y="sales",
    color="product",
    barmode="group",
    title="Sales by Region and Product",
    color_discrete_sequence=["#3B6EAD", "#AFC4E8"]
)

fig.show()

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed